[build]
  base = "docs/"
  command = "./scripts/copy-docs.sh && hugo --gc"

[context.production]
  command = "./scripts/copy-docs.sh && make all"

[context.docs-development]
  command = "./scripts/copy-docs.sh && make all-dev"

[context.docs-staging]
  command = "./scripts/copy-docs.sh && make all-staging"

[context.branch-deploy]
  command = "./scripts/copy-docs.sh && hugo --gc -d public/nginx-service-mesh -b $DEPLOY_PRIME_URL/nginx-service-mesh"

[context.deploy-preview]
  command = "./scripts/copy-docs.sh && hugo --gc -d public/nginx-service-mesh -b $DEPLOY_PRIME_URL/nginx-service-mesh"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-service-mesh/"
  status = 301
  force = true

[[redirects]]
  from = "/nginx-service-mesh/robots.txt"
  to = "https://docs.nginx.com/robots.txt"
  status = 301
  force = true

[[redirects]]
  from = "/nginx-service-mesh/*"
  to = "/nginx-service-mesh/404.html"
  status = 404
